.IFNDEF _GAME_SYMBOLS_
.DEFINE _GAME_SYMBOLS_

.SEGMENT "ZEROPAGE"
OBJ_PTR: .RES 2
.ENDIF

.SEGMENT "OAM"
OAM: .RES 256

.SEGMENT "RAM"
NMI_DONE:    .RES 1
PPUCMDFLAG:  .RES 1
PPUMASKFLAG: .RES 1
PPUCTRLFLAG: .RES 1
OAMFLAG:     .RES 1
SCROLLFLAG:  .RES 1
PPUMASKBUF:  .RES 1
PPUCTRLBUF:  .RES 1
SCROLLX:     .RES 1
SCROLLY:     .RES 1
CMD_RPTR:    .RES 1
CMD_WPTR:    .RES 1
CMDBUF:      .RES 256
ACTOR_RPTR:  .RES 1
ACTOR_WPTR:  .RES 1
ACTORBUF:    .RES 256
JOYPAD1:     .RES 1
JOYPAD2:     .RES 1
JOYPAD3:     .RES 1
JOYPAD4:     .RES 1

Cam: .TAG Camera
Actors: 
    .TAG Actor
    .TAG Actor
    .TAG Actor
    .TAG Actor

.SEGMENT "CODE"
NUM_ACTORS: .BYTE $04

