.SEGMENT "HEADER"
  .BYTE $4E, $45, $53, $1A ; NES 
  .BYTE 2         ; 1 OR 2 FOR NROM-128 OR NROM-256 RESPECTIVELY
  .BYTE 1         ; 8 KIB CHR ROM
  .BYTE $01       ; MAPPER 0; $00 OR $01 FOR HORIZONTAL OR VERTICAL MIRRORING RESPECTIVELY
  .BYTE $08       ; MAPPER 0; NES 2.0
  .BYTE $00       ; NO SUBMAPPER
  .BYTE $00       ; PRG ROM NOT 4 MIB OR LARGER
  .BYTE $00       ; NO PRG RAM
  .BYTE $00       ; NO CHR RAM
  .BYTE $00       ; 0 OR 1 FOR NTSC OR PAL RESPECTIVELY
  .BYTE $00       ; NO SPECIAL PPU